name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/checkout@v2
      with:
        python-version: '3.12'

    - name: Building Image for Testing API
      run: docker build -f Dockerfile.test -t rest-api-app-test .

    - name: Running Tests Image
      run: docker run --rm rest-api-app-test
